### ISSUE TITLE
The meeting invitation are not working as expected

### ISSUE THREAD

**Issue by seba7667** [IsmaelMartinez/teams-for-linux#1370]
When I am trying to join a meeting and my browser redirection is on, the teams app pops up with blue screen and I cannot do anything. I have to completely close the app and start it again.

With the redirector off I can easily join the call on my browser.

The above description is for version 1.8.1

For version 1.9 it looks a little different,
the team's app is reloading and I am going back to the main page with all the chats

Go to the Prospect Mail or OWA and try to join any teams meeting

**Expected behavior**
I should be redirected to the teams call settings and them I should be able to join the call

Logs from the shell script

```
16:21:24.826 › second-instance started
16:21:24.827 › processArgs: [
  '/opt/teams-for-linux/teams-for-linux',
  '--allow-file-access-from-files',
  '--try-supported-channel-layouts',
  '--disable-features=HardwareMediaKeyHandling',
  '--enable-features=WebRTCPipeWireCapturer',
  '--use-fake-ui-for-media-stream',
  '--auth-server-whitelist=*',
  '--enable-ntlm-v2=true',
  'msteams://teams.microsoft.com/l/meetup-join/19%3ameeting_ODcyNWM4ZTItOGM3OC00NGQ2LThjNDYtYWIyNTkyYzM5MjU5%40thread.v2/0?context=%7b%22Tid%22%3a%224696b3d7-84b8-4292-9d1a-6d6b14886ed4%22%2c%22Oid%22%3a%22bfe08da8-14b6-4dd3-9123-97118171b7f5%22%7d'
]
16:21:24.827 › testing RegExp processArgs false
16:21:24.827 › testing RegExp processArgs false
16:21:24.827 › testing RegExp processArgs false
16:21:24.827 › testing RegExp processArgs false
16:21:24.827 › testing RegExp processArgs false
16:21:24.828 › testing RegExp processArgs false
16:21:24.828 › testing RegExp processArgs false
16:21:24.828 › testing RegExp processArgs false
16:21:24.828 › testing RegExp processArgs false
16:21:24.828 › A url argument received with msteams protocol
[1620732:0820/162124.856416:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
16:21:25.615 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
16:21:25.792 › did-frame-finish-load {} true
16:21:25.793 › did-finish-load
16:21:26.711 › Badge count set to '0'
16:21:26.721 › Badge count set to '0'
16:21:27.317 › Badge count set to '0'
16:21:28.687 › did-frame-finish-load {} false
16:21:35.630 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
```

**Desktop (please complete the following information):**
 - Installation package [deb, rpm, snap, AppImage, tar.gz, source...]
 - Version [e.g. 0.1.17]

I am running Ubuntu 22.04 LTS

**Comment by IsmaelMartinez** [comment]
This looks similar to this https://github.com/electron/electron/issues/32760 and https://github.com/IsmaelMartinez/teams-for-linux/issues/1369. I will see if applying the fix expressed in https://github.com/IsmaelMartinez/teams-for-linux/issues/1369 works. In the meantime, can you try running with --disableGpu . 

You will need that flag to test the fix. I hope I can get if out soon.

**Comment by IsmaelMartinez** [comment]
Ok, this should be fixed in [pre-release 1.9.1](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.9.1) . Can you validate it? Thanks! 

Apologies as the issue closed as I merged the fix (one of those auto close that I don't want/need all times). Automation... works until it does.

**Comment by seba7667** [comment]
I updated to version 1.9.1(using snap) but still I see the same issue.
Can you kindly confirm how can I run it with disableGpu option?

**Comment by IsmaelMartinez** [comment]
Hi @seba7667 , I can see the logs are for a second instance (meaning, you got the app already running), what is fine but hides a bit of information.

If you can close the app and run it from the terminal like this:

```
teams-for-linux --disableGpu --logConfig={} --webDebug
```

Then put the logs in here (hide any PII if there is any) .

The logs will also indicate where your config.json file is located. You can create that file to persist those extra arguments you might need. You can get the config options by just running `teams-for-linux --help` but are also documented in https://github.com/IsmaelMartinez/teams-for-linux/blob/80f14c0f3d17f28384337fa03399aa46460345a9/app/config/README.md 

Look at the section if you want to make a permanent change (like always running the app with some of the config options)

<img width="1056" alt="image" src="https://github.com/user-attachments/assets/1da0cac4-24f0-4e5e-b241-990249cfe275">

**Comment by seba7667** [comment]
Still the same issue:
Logs:
` teams-for-linux --disableGpu --logConfig={} --webDebug
No config file found, using default values
all good with appLogLevels you aren't using them
Initialising logger with config: "{}"
Logger initialised with transports: {}
12:25:09.469 › File logging at /home/sebastianpustelnik/snap/teams-for-linux/658/.config/teams-for-linux/logs/main.log with level silly
12:25:09.470 › Console logging enabled with level silly
12:25:09.470 › Logger initialised
12:25:09.470 › configPath: /home/sebastianpustelnik/snap/teams-for-linux/658/.config/teams-for-linux
12:25:09.470 › configFile: {}
12:25:09.472 › Running under Wayland, switching to PipeWire...
12:25:09.472 › Disabling GPU support...
dbus-send: /snap/teams-for-linux/658/lib/x86_64-linux-gnu/libdbus-1.so.3: version `LIBDBUS_PRIVATE_1.12.20' not found (required by dbus-send)

(teams-for-linux:872934): Gtk-WARNING **: 12:25:09.560: Theme parsing error: gtk.css:1413:23: 'font-feature-settings' is not a valid property name

(teams-for-linux:872934): Gtk-WARNING **: 12:25:09.562: Theme parsing error: gtk.css:3286:25: 'font-feature-settings' is not a valid property name

(teams-for-linux:872934): Gtk-WARNING **: 12:25:09.563: Theme parsing error: gtk.css:3748:23: 'font-feature-settings' is not a valid property name
MESA-LOADER: failed to open iris (search paths /snap/teams-for-linux/658/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load driver: iris
MESA-LOADER: failed to open kms_swrast (search paths /snap/teams-for-linux/658/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast (search paths /snap/teams-for-linux/658/gnome-platform/usr/lib/x86_64-linux-gnu/dri)
failed to load swrast driver
12:25:10.188 › processArgs: [
  '/snap/teams-for-linux/658/teams-for-linux',
  '--disableGpu',
  '--logConfig={}',
  '--webDebug',
  '--no-sandbox'
]
12:25:10.189 › testing RegExp processArgs false
12:25:10.189 › testing RegExp processArgs false
12:25:10.189 › testing RegExp processArgs false
12:25:10.189 › testing RegExp processArgs false
12:25:10.190 › testing RegExp processArgs false
12:25:10.190 › Testing network using net.request() for https://teams.microsoft.com/v2
12:25:10.191 › Spellchecker is disabled!

(teams-for-linux:872934): Gtk-WARNING **: 12:25:10.232: Theme parsing error: gtk-dark.css:1413:23: 'font-feature-settings' is not a valid property name

(teams-for-linux:872934): Gtk-WARNING **: 12:25:10.236: Theme parsing error: gtk-dark.css:3286:25: 'font-feature-settings' is not a valid property name

(teams-for-linux:872934): Gtk-WARNING **: 12:25:10.237: Theme parsing error: gtk-dark.css:3748:23: 'font-feature-settings' is not a valid property name
[872934:0822/122510.423316:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.login1.Manager.Inhibit: object_path= /org/freedesktop/login1: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.363" (uid=1000 pid=872934 comm="/snap/teams-for-linux/658/teams-for-linux --disabl" label="snap.teams-for-linux.teams-for-linux (enforce)") interface="org.freedesktop.login1.Manager" member="Inhibit" error name="(unset)" requested_reply="0" destination="org.freedesktop.login1" (uid=0 pid=703 comm="/lib/systemd/systemd-logind " label="unconfined")
12:25:10.777 › Network test successful with method https
12:25:11.193 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[872934:0822/122511.225481:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
[872934:0822/122511.683968:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
12:25:12.373 › did-frame-finish-load {} true
12:25:12.373 › did-finish-load
12:25:14.138 › Badge count set to '0'
12:25:14.159 › Badge count set to '0'
12:25:15.302 › Badge count set to '0'
12:25:17.757 › did-frame-finish-load {} false
[872934:0822/122517.763445:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
12:25:21.527 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
12:25:22.731 › did-frame-finish-load {} false
[872934:0822/122522.910271:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
12:25:23.441 › did-frame-finish-load {} false
12:25:31.528 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
12:25:41.530 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
12:25:51.532 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
12:25:59.912 › second-instance started
12:25:59.912 › processArgs: [
  '/snap/teams-for-linux/658/teams-for-linux',
  '--no-sandbox',
  '--allow-file-access-from-files',
  '--try-supported-channel-layouts',
  '--disable-features=HardwareMediaKeyHandling',
  '--enable-features=WebRTCPipeWireCapturer',
  '--use-fake-ui-for-media-stream',
  '--auth-server-whitelist=*',
  '--enable-ntlm-v2=true',
  'msteams://teams.microsoft.com/l/meetup-join/19%3ameeting_ODcyNWM4ZTItOGM3OC00NGQ2LThjNDYtYWIyNTkyYzM5MjU5%40thread.v2/0?context=%7b%22Tid%22%3a%224696b3d7-84b8-4292-9d1a-6d6b14886ed4%22%2c%22Oid%22%3a%22bfe08da8-14b6-4dd3-9123-97118171b7f5%22%7d'
]
12:25:59.913 › testing RegExp processArgs false
12:25:59.913 › testing RegExp processArgs false
12:25:59.913 › testing RegExp processArgs false
12:25:59.913 › testing RegExp processArgs false
12:25:59.913 › testing RegExp processArgs false
12:25:59.914 › testing RegExp processArgs false
12:25:59.914 › testing RegExp processArgs false
12:25:59.914 › testing RegExp processArgs false
12:25:59.914 › testing RegExp processArgs false
12:25:59.914 › testing RegExp processArgs false
12:25:59.914 › A url argument received with msteams protocol
12:26:00.303 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
12:26:00.878 › did-frame-finish-load {} true
12:26:00.878 › did-finish-load
12:26:02.734 › Badge count set to '0'
12:26:02.753 › Badge count set to '0'
12:26:04.261 › Badge count set to '0'
12:26:06.068 › did-frame-finish-load {} false
[872934:0822/122606.071069:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
12:26:10.370 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
12:26:20.373 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
12:26:30.484 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
`

**Comment by IsmaelMartinez** [comment]
are you able to try another packaging system? maybe deb. Snap can be a bit iffy depending on configurations.

Your logs also indicate you got some MESA errors (drivers probably). But it could be just related to been running in snap confinement. 

Try also copy/pasting the meeting link into your chat (in teams) and click from there to see what happens. Not as a final solution but as a temporary workaround.

**Comment by seba7667** [comment]
Still the same Issue, fresh logs:

/opt/teams-for-linux/teams-for-linux --disableGpu --logConfig={} --webDebug
No config file found, using default values
all good with appLogLevels you aren't using them
Initialising logger with config: "{}"
Logger initialised with transports: {}
13:12:14.647 › File logging at /home/sebastianpustelnik/.config/teams-for-linux/logs/main.log with level silly
13:12:14.648 › Console logging enabled with level silly
13:12:14.649 › Logger initialised
13:12:14.649 › configPath: /home/sebastianpustelnik/.config/teams-for-linux
13:12:14.649 › configFile: {}
13:12:14.651 › Running under Wayland, switching to PipeWire...
13:12:14.651 › Disabling GPU support...
13:12:14.839 › processArgs: [
  '/opt/teams-for-linux/teams-for-linux',
  '--disableGpu',
  '--logConfig={}',
  '--webDebug'
]
13:12:14.840 › testing RegExp processArgs false
13:12:14.840 › testing RegExp processArgs false
13:12:14.840 › testing RegExp processArgs false
13:12:14.840 › testing RegExp processArgs false
13:12:14.841 › Testing network using net.request() for https://teams.microsoft.com/v2
13:12:14.842 › Spellchecker is disabled!
13:12:15.362 › Network test successful with method https
13:12:15.654 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[895443:0822/131215.655531:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
[895443:0822/131215.655603:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
13:12:16.275 › did-frame-finish-load {} true
13:12:16.276 › did-finish-load
13:12:18.015 › Badge count set to '0'
13:12:18.033 › Badge count set to '0'
13:12:19.066 › Badge count set to '0'
[895443:0822/131221.157243:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
13:12:21.162 › did-frame-finish-load {} false
13:12:25.740 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
13:12:28.326 › second-instance started
13:12:28.326 › processArgs: [
  '/opt/teams-for-linux/teams-for-linux',
  '--allow-file-access-from-files',
  '--try-supported-channel-layouts',
  '--disable-features=HardwareMediaKeyHandling',
  '--enable-features=WebRTCPipeWireCapturer',
  '--use-fake-ui-for-media-stream',
  '--auth-server-whitelist=*',
  '--enable-ntlm-v2=true',
  'msteams://teams.microsoft.com/l/meetup-join/19%3ameeting_ODcyNWM4ZTItOGM3OC00NGQ2LThjNDYtYWIyNTkyYzM5MjU5%40thread.v2/0?context=%7b%22Tid%22%3a%224696b3d7-84b8-4292-9d1a-6d6b14886ed4%22%2c%22Oid%22%3a%22bfe08da8-14b6-4dd3-9123-97118171b7f5%22%7d'
]
13:12:28.327 › testing RegExp processArgs false
13:12:28.327 › testing RegExp processArgs false
13:12:28.327 › testing RegExp processArgs false
13:12:28.327 › testing RegExp processArgs false
13:12:28.327 › testing RegExp processArgs false
13:12:28.327 › testing RegExp processArgs false
13:12:28.328 › testing RegExp processArgs false
13:12:28.328 › testing RegExp processArgs false
13:12:28.328 › testing RegExp processArgs false
13:12:28.328 › A url argument received with msteams protocol
13:12:28.716 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
13:12:29.342 › did-frame-finish-load {} true
13:12:29.343 › did-finish-load
13:12:34.554 › Badge count set to '0'
13:12:34.594 › Badge count set to '0'
13:12:35.496 › Badge count set to '0'
[895443:0822/131237.578822:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
13:12:37.584 › did-frame-finish-load {} false
13:12:38.793 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'


^C13:12:47.955 › before-quit
13:12:47.955 › window close
13:12:48.064 › window closed
13:12:48.064 › will-quit
13:12:48.064 › quit


Thanks for a tip about workaround, it's working!

**Comment by IsmaelMartinez** [comment]
I think there is a wee bug in the code that the `msteams://` is expected as `msteams:/` (or the other way around) so it changes the url incorrectly to have an extra `/` but I will need to have a look.

**Comment by IsmaelMartinez** [comment]
I think this is similar as #1373 and it should be fixed with https://github.com/IsmaelMartinez/teams-for-linux/pull/1376

**Comment by IsmaelMartinez** [comment]
Can you check the pre-release https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.9.3 ? I think this would fix it for you.

**Comment by seba7667** [comment]
hey,
now it's the same behavior as on the 1.8.1, blue screen.
Fresh logs:
/opt/teams-for-linux/teams-for-linux --disableGpu --logConfig={} --webDebug
No config file found, using default values
all good with appLogLevels you aren't using them
Initialising logger with config: "{}"
Logger initialised with transports: {}
11:15:50.161 › File logging at /home/sebastianpustelnik/.config/teams-for-linux/logs/main.log with level silly
11:15:50.162 › Console logging enabled with level silly
11:15:50.162 › Logger initialised
11:15:50.162 › configPath: /home/sebastianpustelnik/.config/teams-for-linux
11:15:50.162 › configFile: {}
11:15:50.164 › Running under Wayland, switching to PipeWire...
11:15:50.164 › Disabling GPU support...
11:15:50.348 › processArgs: [
  '/opt/teams-for-linux/teams-for-linux',
  '--disableGpu',
  '--logConfig={}',
  '--webDebug'
]
11:15:50.349 › testing RegExp processArgs false
11:15:50.349 › testing RegExp processArgs false
11:15:50.349 › testing RegExp processArgs false
11:15:50.350 › testing RegExp processArgs false
11:15:50.350 › Testing network using net.request() for https://teams.microsoft.com
11:15:50.352 › Spellchecker is disabled!
11:15:50.755 › Network test successful with method https
11:15:51.098 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[1379902:0823/111551.099808:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
[1379902:0823/111551.103786:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
11:15:52.210 › did-frame-finish-load {} true
11:15:52.211 › did-finish-load
11:15:54.071 › Badge count set to '0'
11:15:54.088 › Badge count set to '0'
11:15:55.137 › Badge count set to '0'
[1379902:0823/111557.597344:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
11:15:57.608 › did-frame-finish-load {} false
11:16:00.493 › did-frame-finish-load {} false
[1379902:0823/111600.771261:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
11:16:00.842 › did-frame-finish-load {} false
11:16:01.175 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
11:16:04.377 › second-instance started
11:16:04.377 › processArgs: [
  '/opt/teams-for-linux/teams-for-linux',
  '--allow-file-access-from-files',
  '--try-supported-channel-layouts',
  '--disable-features=HardwareMediaKeyHandling',
  '--enable-features=WebRTCPipeWireCapturer',
  '--use-fake-ui-for-media-stream',
  '--auth-server-whitelist=*',
  '--enable-ntlm-v2=true',
  'msteams://teams.microsoft.com/l/meetup-join/19%3ameeting_ODcyNWM4ZTItOGM3OC00NGQ2LThjNDYtYWIyNTkyYzM5MjU5%40thread.v2/0?context=%7b%22Tid%22%3a%224696b3d7-84b8-4292-9d1a-6d6b14886ed4%22%2c%22Oid%22%3a%22bfe08da8-14b6-4dd3-9123-97118171b7f5%22%7d'
]
11:16:04.378 › testing RegExp processArgs false
11:16:04.378 › testing RegExp processArgs false
11:16:04.378 › testing RegExp processArgs false
11:16:04.378 › testing RegExp processArgs false
11:16:04.378 › testing RegExp processArgs false
11:16:04.378 › testing RegExp processArgs false
11:16:04.378 › testing RegExp processArgs false
11:16:04.378 › testing RegExp processArgs false
11:16:04.378 › testing RegExp processArgs false
11:16:04.379 › A url argument received with msteams protocol
11:16:04.782 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
11:16:04.784 › did-frame-finish-load {} true
11:16:04.864 › did-finish-load
11:16:14.786 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
11:16:24.788 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'


Additionaly in the developers console I see following issues:
![image](https://github.com/user-attachments/assets/5189e629-1c3e-48ca-a9b3-baa6023e18eb)

**Comment by IsmaelMartinez** [comment]
ok, I can see and confirms what I was thinking. 

Basically a v1 to v2 change. msteams links use to be `msteams:/l/meetup-join/` but now are `msteams://teams.microsoft.com/l/meetup-join/` 

On the previous links I use to change `msteams:/` for the config.url `https://teams.microsoft.com/` but that change now is creating that double teams.microsoft.com 

I will see if I can fix it and put a pre-release today. Thanks for the logs!

**Comment by IsmaelMartinez** [comment]
can you try  https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.9.4 ?  Thanks

**Comment by IsmaelMartinez** [comment]
also, I think your company must be using teams-v2 so you might need to start with the following config:

```
{
   "disableGpu": true,
   "url": "https://teams.microsoft.com/v2",
   "optInTeamsV2": true
}
```

**Comment by seba7667** [comment]
Man, you are legend!!!
Now it's working fine!!!
FYI I don't need to change any settings, it's working fine with everything defaulted.

**Comment by IsmaelMartinez** [comment]
so. then microsoft just changed those links. Really strange as I never get those links neither on emails nor on calendar invites ... anyway, glad is working. I will mark it as solved and close.
