### ISSUE TITLE
Log full with messages about YUV_420_BIPLANAR, usage=SCANOUT_CPU_READ_WRITE, buffer and mailbox

### ISSUE THREAD

**Issue by janvlug** [IsmaelMartinez/teams-for-linux#1489]
I see many times per second this message in the logs:

```
Nov 21 09:30:35 nyx com.github.IsmaelMartinez.teams_for_linux.desktop[2263981]: [55:1121/093035.193767:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= YUV_420_BIPLANAR and usage=SCANOUT_CPU_READ_WRITE
Nov 21 09:30:35 nyx com.github.IsmaelMartinez.teams_for_linux.desktop[2263981]: [55:1121/093035.193979:ERROR:gpu_channel.cc(503)] Buffer Handle is null.
Nov 21 09:30:35 nyx com.github.IsmaelMartinez.teams_for_linux.desktop[2264060]: [132:1121/093035.194231:ERROR:shared_image_interface_proxy.cc(134)] Buffer handle is null. Not creating a mailbox from it.
```

One time I saw this (maybe this is related):
```
Nov 21 09:30:35 nyx com.github.IsmaelMartinez.teams_for_linux.desktop[2264060]: [132:1121/093035.288736:ERROR:sdp_offer_answer.cc(424)] A BUNDLE group contains a codec collision for payload_type='101. All codecs must share the same type, encoding name, clock rate and parameters. (INVALID_PARAMETER)
```

I use Fedora 41, GNOME Wayland.
```
Portal for Teams	com.github.IsmaelMartinez.teams_for_linux	1.11.5	stable	flathub	system
```

**Comment by IsmaelMartinez** [comment]
Hi @janvlug , can you try a non flathub version? I suspect this is a problem with some drivers and your flatpak. 

You can see the other packages in here https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.11.5

**Comment by IsmaelMartinez** [comment]
check also https://github.com/IsmaelMartinez/teams-for-linux/issues/1331 as I suspect you are not able to do screenshare with that error, but it is either flatpak, drivers or wayland creating this problem.

**Comment by amorsen** [comment]
The problem exists in Chromium as well, where it is fixed in 131.0.6738.0.

https://issuetracker.google.com/issues/331796411

**Comment by IsmaelMartinez** [comment]
Nice find. Hopefully electron releases a new version soon with that
chromium.

**Comment by IsmaelMartinez** [comment]
electron 33 is in the 130 branch. Hopefully they do a regression fix in the 130, otherwise we will need to go to electron 34 that is in beta.

**Comment by nsballmann** [comment]
In MS Edge 131 (based on Chromium) with Teams PWA the screen sharing issue started to appear. Downgrading to 130 makes it work again.

Hence maybe in the Teams PWA they worked around some issue that was present in 130 but isn't anymore due to the mentioned patch? So maybe the workaround broke?

**Comment by nsballmann** [comment]
Ah and in MS Edge 132, which is in dev preview, it's still present.

**Comment by IsmaelMartinez** [comment]
closing as the issue 1st reported is different that the one we are currently discussing (that has anotehr issue open).
