### ISSUE TITLE
[Bug]: Screen sharing is blurry for some windows and others not.

### ISSUE THREAD

**Issue by yorick1989** [IsmaelMartinez/teams-for-linux#1849]
### Can you reproduce this bug in the website/PWA?

Not applicable

### Describe the bug

Screen sharing is blurry for some windows and others not.

### What package are you using?

aur

### Version

2.2.1-1

### Reproduction steps

```markdown
1. Screen share a specific window (in this case Steam)
```

### Expected Behavior

```markdown
1. The screen share not to be blurry.
```

### Debug

```markdown
ELECTRON_ENABLE_LOGGING=true teams-for-linux --logConfig='{}'
...
16904:0927/052743.134261:INFO:CONSOLE:43] "Screen sharing status: true Source ID: window:100663353:0", source: file:///opt/teams-for-linux/resources/app.asar/app/inAppUI/callPopOut.html (43)
[16904:0927/052743.159168:INFO:CONSOLE:91] "Resizing thumbnail to: 400 x 225 for video: 192 x 108", source: file:///opt/teams-for-linux/resources/app.asar/app/inAppUI/callPopOut.html (91)
05:27:46.555 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[16904:0927/052746.556487:INFO:CONSOLE:1] "setMachineState teams2 state=1", source: https://teams.microsoft.com/v2/ (1)
...
[16904:0927/052805.285913:INFO:CONSOLE:43] "Screen sharing status: true Source ID: window:23068675:0", source: file:///opt/teams-for-linux/resources/app.asar/app/inAppUI/callPopOut.html (43)
[16904:0927/052805.301879:INFO:CONSOLE:91] "Resizing thumbnail to: 400 x 225 for video: 1920 x 1080", source: file:///opt/teams-for-linux/resources/app.asar/app/inAppUI/callPopOut.html (91)
[16904:0927/052805.306230:ERROR:third_party/webrtc/modules/desktop_capture/linux/x11/window_list_utils.cc:62] Failed to query for child windows although windowdoes not have a valid WM_STATE.
05:28:06.567 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[16904:0927/052806.568111:INFO:CONSOLE:1] "setMachineState teams2 state=1", source: https://teams.microsoft.com/v2/ (1)
```

### Additional context

It seems like that in some cases window sharing is not working properly and is blurry. It interprets the blurry screen in a lower resolution than it actually has.

Check the screenshots below for the differences.

<img width="1743" height="995" alt="Image" src="https://github.com/user-attachments/assets/8177d532-76a1-49f6-a62f-e6863ce751c5" />
<img width="1817" height="842" alt="Image" src="https://github.com/user-attachments/assets/8e45eaff-dbd1-4acc-ac65-572f3e3de5a1" />

Also, the terminal that did fine during screen sharing the first time can also have issues during the next screen sharing session (in a newly created meeting).

**Comment by IsmaelMartinez** [comment]
Hi @yorick1989 and thanks for reporting this. 

Can you check a couple of things?

* Check if the people that are seeing your screenshared content do get the blurred version, or if this is just the preview(popOut) screen.
* Check if the pre-releases https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v2.5.8 has the same issue.

I do suspect is only the pre-view screen, not the actual sharing, but surprised and might be something else. Check if you got any warning and/or errors in the logs. It could be a hardware acceleration issue also. If you put more logs I can have a look. 

Thanks and let me know how you get along

**Comment by yorick1989** [comment]
Hi @IsmaelMartinez , 

it seems like version 2.8.5 is working properly, but I'd the message 'Error: Invalid state' now myself in the preview window:

<img width="341" height="218" alt="Image" src="https://github.com/user-attachments/assets/1f14998f-0eab-4a8f-8fd9-41080d38cc7e" />

I can live with that, but just a FWI. And do you know when this version is released for Arch Linux as an AUR package?

Thanks!

**Comment by IsmaelMartinez** [comment]
Hi @yorick1989 , 

That `Invalid state` can just be cache or something fixed in later versions.

I am trying to fix a few niggling issues like #1847, #1800 and a few others, then I will make it as a release.

Numbering can be a bit confusing but hope to make it stable in the 2.6.x branch (I assume you said 2.5.8 not 2.8.5... and you are coming from the future ;))

Thanks

**Comment by yorick1989** [comment]
Hey @IsmaelMartinez ,

Yes, that is what i meant haha. Do you want me to closer this issue, since you are already working on it and there are other issues open which makes this one redundant. 

You can close it if you think it's obsolete. 

Thanks for the quick responses! 

Grtz, 

Yorick

**Comment by IsmaelMartinez** [comment]
Hi @yorick1989, can you check if https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v2.5.10 fixes this issue? Thanks

**Comment by yorick1989** [comment]
Hi @IsmaelMartinez , I do still get the same error message. Also when I tried the latest pre-release, 2.5.11.

**Comment by IsmaelMartinez** [comment]
the no preview error is been tracked in https://github.com/IsmaelMartinez/teams-for-linux/issues/1853 . If the blurry issue is been fixed, I would prefer to close this issue and we can fix the "invalid state" error in the other one. Thanks for testing and I do hope to have some time to look into this preview issue. It might be the last fix before making it stable again! Taking some time but getting there.
