### ISSUE TITLE
[Bug]: teams-for-linux prevents sleep

### ISSUE THREAD

**Issue by leflamm** [IsmaelMartinez/teams-for-linux#1879]
### Can you reproduce this bug in the website/PWA?

No

### Describe the bug

Sometimes cannot put my computer go to sleep because teams-for-linux inhibits with reason "Application cleanup before suspend"

### What package are you using?

deb

### Version

2.2.1

### Reproduction steps

```markdown
Happens once or twice a week, so once or twice every ~50 attempts to put computer to sleep.

1. Try to get your computer to sleep (in my case Lenovo ThinkPad P1 Gen 4i, Ubuntu 25.04) -> Computer does not go to sleep
2. Find out inhibitors, run `dbus-send --print-reply --dest=org.gnome.SessionManager /org/gnome/SessionManager org.gnome.SessionManager.GetInhibitors` (Example output: `/org/gnome/SessionManager/Inhibitor1641`)
3. Look up specific inhibitor, run `dbus-send --print-reply --dest=org.gnome.SessionManager /org/gnome/SessionManager/Inhibitor1641 org.gnome.SessionManager.Inhibitor.GetAppId` (Example output: `string "/opt/teams-for-linux/teams-for-linux"`)
4. Check for reason, run `systemd-inhibit --list` (output could contain reason "Application cleanup before suspend")
5. quit `teams-for-linux`
6. try again to put computer to sleep -> works
```

### Expected Behavior

```markdown
teams-for-linux would not prevent my computer to go to sleep
```

### Debug

```markdown
Error not reproducible on freshly-stared application
```

**Comment by IsmaelMartinez** [comment]
Hi @leflamm , are you able to provide some logs? it could be that the default `screenLockInhibitionMethod` (electron) is not working for you. Check if the `WakeLockSentinel` option works for you. More info in the config options https://ismaelmartinez.github.io/teams-for-linux/configuration

Hope helps

**Comment by leflamm** [comment]
Will definitely try that option, thanks!

Any specific logs I can grab being in the situation that prevents going to sleep?

**Comment by leflamm** [comment]
Changed to 
``` json
"screenLockInhibitionMethod": "WakeLockSentinel",
```
Does not make a difference. Any idea which logs I can provide once I run into that situation again?

**Comment by IsmaelMartinez** [comment]
regarding the logs, if you can send the logs around the time this happens that will be great. It might be that is already fixed in [2.6.3](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v2.6.3). Could be a side effect of the issue this https://github.com/IsmaelMartinez/teams-for-linux/pull/1878 fixed.

**Comment by kapouer** [comment]
You can get better insight about why gnome is not sleeping with `gnome-session-inhibit --list`.
I had teams (the PWA) opened, and got two
> /usr/lib/chromium/chromium: Download in progress (suspend)

Quitting teams removed them from that list.
Reopening didn't. I suppose I did something (download a file, probably).

**Comment by leflamm** [comment]
> regarding the logs, if you can send the logs around the time this happens that will be great. It might be that is already fixed in [2.6.3](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v2.6.3). Could be a side effect of the issue this [#1878](https://github.com/IsmaelMartinez/teams-for-linux/pull/1878) fixed.

Which logs would be helpful? How do I obtain them? What's the location of the log files? Do I need to enable some/more logging first?

Btw: found out that "right click on the tray icon" > "Refresh" removes the inhibition and then let's my computer go to sleep.

**Comment by IsmaelMartinez** [comment]
can you try the latest version? https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v2.6.11 , there was a bug in the notifications section. Maybe that did make it fail? maybe one of the download dialogs got stuck as the notification didn't happen... just a guess but I think worth a try. Thanks!

**Comment by leflamm** [comment]
I am on 2.6.12 and still have that problem.

Btw the output of `gnome-session-inhibit --list` is:
```
/opt/teams-for-linux/teams-for-linux: Blink Wake Lock (suspend, idle)
```

Do you have any particular log (location?) in mind that I can provide?

**Comment by IsmaelMartinez** [comment]
No idea why this is happening. 

To get logs you need to start the application with the following:

```bash
ELECTRON_ENABLE_LOGGING=true teams-for-linux --logConfig='{}'
```

Without logs I can only make speculations or guesses, so they are incredibly valuable. 

Thanks

**Comment by SlavikZ** [comment]
It looks like a general problem in recent Gnome versions: https://discussion.fedoraproject.org/t/gnome-session-binary-sometimes-blocks-suspend-when-running-emacs/162715/17.

**Comment by IsmaelMartinez** [comment]
Thanks for sharing. This means it is blocked. It might be a chromium/chrome issue. Hopefully they fix it in newer releases and we can use that version. Thanks!

**Comment by SlavikZ** [comment]
It could be a Gnome issue: https://gitlab.gnome.org/GNOME/gnome-session/-/issues/174#note_2571322

**Comment by magist3r** [comment]
I have a similar issue on Kubuntu 24.04. When teams app is opened, sometimes my Lenovo laptop won't sleep. I'll try to provide additional logs later.

**Comment by magist3r** [comment]
Looks like the issue is reproducible only after a call, and it only inhibits sleep and screen lock by timer. Sleep from the menu always works. I'll start teams with logs enabled and see what I can find.

**Comment by magist3r** [comment]
So yes, it happens after a call:
```
[285623:0113/134741.967986:INFO:CONSOLE:16] "setMachineState teams2 state=1", source: https://teams.microsoft.com/v2/ (16)
[285623:0113/134751.969465:INFO:CONSOLE:16] "setMachineState teams2 state=1", source: https://teams.microsoft.com/v2/ (16)
[285623:0113/134801.971550:INFO:CONSOLE:16] "setMachineState teams2 state=1", source: https://teams.microsoft.com/v2/ (16)
[285623:0113/134811.973051:INFO:CONSOLE:16] "setMachineState teams2 state=1", source: https://teams.microsoft.com/v2/ (16) 
```
**Call ended here**
```
13:48:21.974 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 302s, IdleState: 'idle'
[285623:0113/134821.976490:INFO:CONSOLE:16] "setMachineState teams2 state=2", source: https://teams.microsoft.com/v2/ (16)
13:48:24.006 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 304s, IdleState: 'idle'
[285623:0113/134824.008372:INFO:CONSOLE:16] "setMachineState teams2 state=2", source: https://teams.microsoft.com/v2/ (16)
13:48:26.009 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 306s, IdleState: 'idle'
[285623:0113/134826.010798:INFO:CONSOLE:16] "setMachineState teams2 state=2", source: https://teams.microsoft.com/v2/ (16)
```
And these messages keeps repeating every 2s.

**Comment by magist3r** [comment]
Yesterday it worked properly I suppose (switched from **idle** to **locked** after 900s)
```
[285623:0112/194049.184707:INFO:CONSOLE:16] "setMachineState teams2 state=2", source: https://teams.microsoft.com/v2/ (16)
19:40:51.184 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 900s, IdleState: 'idle'
[285623:0112/194051.185568:INFO:CONSOLE:16] "setMachineState teams2 state=2", source: https://teams.microsoft.com/v2/ (16)
19:40:53.186 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 902s, IdleState: 'locked'
```
But today after a call it kept going forever:
```
[285623:0113/232242.915842:INFO:CONSOLE:16] "setMachineState teams2 state=2", source: https://teams.microsoft.com/v2/ (16)
23:22:44.916 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 7299s, IdleState: 'idle'
[285623:0113/232244.917258:INFO:CONSOLE:16] "setMachineState teams2 state=2", source: https://teams.microsoft.com/v2/ (16)
23:22:46.917 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 7301s, IdleState: 'idle'
```

**Comment by IsmaelMartinez** [comment]
It might be good to report it to those other project open issues, as I suspect it is not related to our app. It might help them identify what it is failing. It is probably a drivers issue or similar. Thanks for the logs!
