### ISSUE TITLE
Screen sharing leads to crash (wayland)

### ISSUE THREAD

**Issue by Michsior14** [IsmaelMartinez/teams-for-linux#886]
**Describe the bug**
Screen sharing doesn't work in wayland sessions after the electron update. This is due to long standing bug in electron: https://github.com/electron/electron/issues/37463. There is a fix on the way, but it's not yet merged unfortunately: https://github.com/electron/electron/pull/38833.

**To Reproduce**
1. Go to any meeting
2. Click on window screen share

**Expected behavior**
Screen sharing works without issues

**Desktop (please complete the following information):**
 - OS: Fedora (doesn't matter, all OSes with Wayland enabled are affected)
 - Installation package: Flatpak (doesn't matter, all packages affected) 
 - Version: 1.2.2

**Comment by maymage** [comment]
Related 

* https://github.com/electron/electron/issues/37463
* https://github.com/electron/electron/pull/38833

**Comment by parraletz** [comment]
The same issue in Archlinux and Ubuntu 22.04

**Comment by jijojosephk** [comment]
It's a problem in `chromium` not sure it is fixed.

**Comment by ShinZaibatsu** [comment]
Just started to see this issue on my system as well.
Fedora 37 - Wayland.

**Comment by Michsior14** [comment]
> It's a problem in `chromium` not sure it is fixed.

It's an `electron` bug, not `chromium` as described in the bug report.

**Comment by ruet-blum** [comment]
Same issue on Debian 12, Gnome 43.4, Wayland

**Comment by stdevel** [comment]
Same here on Fedora 38, GNOME 44.2, Wayland, teams-for-linux 1.2.3 (*1.2.4 changelog doesn't mention this issue*). Error message:

```
[ERROR] connect ECONNREFUSED ::1:80
[169917:0711/114347.927996:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
[170053:0711/114349.756925:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[170053:0711/114407.550378:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[170053:0711/114408.954844:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

**Comment by maymage** [comment]
The [fix](https://github.com/IsmaelMartinez/teams-for-linux/issues/886#issuecomment-1627129738) got just merged and backported to electron 24+

**Comment by jijojosephk** [comment]
Version `1.2.*` is using electron version `24.6.2` so it must be fixed. Try the deb,rpm or other native packages to test. `snap` is having issues with wayland. Not sure about `flatpak`

**Comment by Michsior14** [comment]
> Version `1.2.*` is using electron version `24.6.2` so it must be fixed. Try the deb,rpm or other native packages to test. `snap` is having issues with wayland. Not sure about `flatpak`

The fix has not been released yet on electron side, just merged ;)

**Comment by PocketSam** [comment]
Didn't try it myself but previous version seemed to work well.
One can try to rollback the previous version v1.2.2 (efa4c393) with
flatpak update --commit=3f312500cf2d9d58cbf5c737cd86b330f370d74ff7758a7866b8d6ed04cc8e51 com.github.IsmaelMartinez.teams_for_linux

You can find required version with
flatpak remote-info --log flathub com.github.IsmaelMartinez.teams_for_linux

**Comment by AccaliaDeElementia** [comment]
rolling back to 3f312500 as PocketSam suggested did not resolve the crashes, but rolling back to the version before that did.

Executing the below allowed me to roll back and returned the ability to share screen while I wait for the upstream electron bugfix to be released and merged into this project.

> flatpak update --commit=db996749122e6e74b2883d5c1b101ca760f01fa5425936ac24ee5c263c4437c8 com.github.IsmaelMartinez.teams_for_linux

**Comment by jijojosephk** [comment]
> rolling back to 3f312500 as PocketSam suggested did not resolve the crashes, but rolling back to the version before that did.
> 
> Executing the below allowed me to roll back and returned the ability to share screen while I wait for the upstream electron bugfix to be released and merged into this project.
> 
> > flatpak update --commit=db996749122e6e74b2883d5c1b101ca760f01fa5425936ac24ee5c263c4437c8 com.github.IsmaelMartinez.teams_for_linux

You might have seen missing tray icon as well. Something's not working for SNI icons when sandboxed. Could not find anything in logs as well. Rabbit hole!

**Comment by brodowskid** [comment]
It looks that the electron bug has been been fixed with electron 24.6.3 and 25.3.0.

**Comment by bss-markus-schulze** [comment]
Silly question: will there be e new version of teams-for-linux where this crash is fixed ?

**Comment by jijojosephk** [comment]
@bss-markus-schulze you may check `1.2.5`

**Comment by robhancocksed** [comment]
Well screen sharing doesn't seem to crash the app anymore with 1.2.5, but unfortunately it seems like the option to share individual windows has gone away. It only seems to offer to share the entire monitor.

**Comment by bss-markus-schulze** [comment]
Yepp, same here.

I asume the place to pick the screen should have been in this new bottom area, but the Gnome windows still appears:
![Bildschirmfoto vom 2023-07-18 07-41-17](https://github.com/IsmaelMartinez/teams-for-linux/assets/78405591/97a78fdd-7cab-4be4-b886-ec3d20a2b891)

Clicking on Windows doesn't show any option to pick:
![Bildschirmfoto vom 2023-07-18 07-41-30](https://github.com/IsmaelMartinez/teams-for-linux/assets/78405591/4e2574db-c0a7-4458-ae92-00a137512dca)

I'm on Fedora 38 Gnome Wayland Pipewire, if that's relevant.
